/*

 FORESTBG.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 32
   Tile set      : knight_background_sprites.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 38
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __ForestBG_h_INCLUDE
#define __ForestBG_h_INCLUDE

#define ForestBGWidth 20
#define ForestBGHeight 32
#define ForestBGBank 0

#define ForestBG ForestBGPLN0
extern const unsigned char ForestBGPLN0[];
extern const unsigned char ForestBGPLN1[];

#endif

/* End of FORESTBG.H */
