/*

 GAMEOVERBACKGROUND.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : Z:\home\rafagars\gbdk\GBTD\BackgroundTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __GameOverBackground_h_INCLUDE
#define __GameOverBackground_h_INCLUDE

#define GameOverWidth 20
#define GameOverHeight 18
#define GameOverBank 0

extern const unsigned char GameOver[];

#endif

/* End of GAMEOVERBACKGROUND.H */
