/*

 KNIGHT_TILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 12

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __knight_tiles_h_INCLUDE
#define __knight_tiles_h_INCLUDE

/* Bank of tiles. */
#define Knight_tilesBank 0

/* Super Gameboy palette 0 */
#define Knight_tilesSGBPal0c0 6076
#define Knight_tilesSGBPal0c1 8935
#define Knight_tilesSGBPal0c2 6596
#define Knight_tilesSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define Knight_tilesSGBPal1c0 6076
#define Knight_tilesSGBPal1c1 8935
#define Knight_tilesSGBPal1c2 6596
#define Knight_tilesSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define Knight_tilesSGBPal2c0 6076
#define Knight_tilesSGBPal2c1 8935
#define Knight_tilesSGBPal2c2 6596
#define Knight_tilesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define Knight_tilesSGBPal3c0 6076
#define Knight_tilesSGBPal3c1 8935
#define Knight_tilesSGBPal3c2 6596
#define Knight_tilesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define Knight_tilesCGBPal0c0 23454
#define Knight_tilesCGBPal0c1 12272
#define Knight_tilesCGBPal0c2 6596
#define Knight_tilesCGBPal0c3 5344

/* Gameboy Color palette 1 */
#define Knight_tilesCGBPal1c0 30687
#define Knight_tilesCGBPal1c1 15326
#define Knight_tilesCGBPal1c2 825
#define Knight_tilesCGBPal1c3 0

/* Gameboy Color palette 2 */
#define Knight_tilesCGBPal2c0 32767
#define Knight_tilesCGBPal2c1 95
#define Knight_tilesCGBPal2c2 113
#define Knight_tilesCGBPal2c3 1

/* Gameboy Color palette 3 */
#define Knight_tilesCGBPal3c0 6076
#define Knight_tilesCGBPal3c1 8935
#define Knight_tilesCGBPal3c2 6596
#define Knight_tilesCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define Knight_tilesCGBPal4c0 6076
#define Knight_tilesCGBPal4c1 8935
#define Knight_tilesCGBPal4c2 6596
#define Knight_tilesCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define Knight_tilesCGBPal5c0 6076
#define Knight_tilesCGBPal5c1 8935
#define Knight_tilesCGBPal5c2 6596
#define Knight_tilesCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define Knight_tilesCGBPal6c0 6076
#define Knight_tilesCGBPal6c1 8935
#define Knight_tilesCGBPal6c2 6596
#define Knight_tilesCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define Knight_tilesCGBPal7c0 6076
#define Knight_tilesCGBPal7c1 8935
#define Knight_tilesCGBPal7c2 6596
#define Knight_tilesCGBPal7c3 5344
/* CGBpalette entries. */
extern const unsigned char Knight_tilesCGB[];
/* Start of tile array. */
extern const unsigned char Knight_tiles[];

#endif

/* End of KNIGHT_TILES.H */
