/*

 KNIGHT_SPRITES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 30

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __knight_sprites_h_INCLUDE
#define __knight_sprites_h_INCLUDE

/* Bank of tiles. */
#define knight_spritesBank 0

/* Super Gameboy palette 0 */
#define knight_spritesSGBPal0c0 6076
#define knight_spritesSGBPal0c1 8935
#define knight_spritesSGBPal0c2 6596
#define knight_spritesSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define knight_spritesSGBPal1c0 6076
#define knight_spritesSGBPal1c1 8935
#define knight_spritesSGBPal1c2 6596
#define knight_spritesSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define knight_spritesSGBPal2c0 6076
#define knight_spritesSGBPal2c1 8935
#define knight_spritesSGBPal2c2 6596
#define knight_spritesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define knight_spritesSGBPal3c0 6076
#define knight_spritesSGBPal3c1 8935
#define knight_spritesSGBPal3c2 6596
#define knight_spritesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define knight_spritesCGBPal0c0 31507
#define knight_spritesCGBPal0c1 32365
#define knight_spritesCGBPal0c2 16609
#define knight_spritesCGBPal0c3 0

/* Gameboy Color palette 1 */
#define knight_spritesCGBPal1c0 15326
#define knight_spritesCGBPal1c1 825
#define knight_spritesCGBPal1c2 626
#define knight_spritesCGBPal1c3 99

/* Gameboy Color palette 2 */
#define knight_spritesCGBPal2c0 18078
#define knight_spritesCGBPal2c1 95
#define knight_spritesCGBPal2c2 113
#define knight_spritesCGBPal2c3 2

/* Gameboy Color palette 3 */
#define knight_spritesCGBPal3c0 29661
#define knight_spritesCGBPal3c1 30680
#define knight_spritesCGBPal3c2 1226
#define knight_spritesCGBPal3c3 0

/* Gameboy Color palette 4 */
#define knight_spritesCGBPal4c0 6076
#define knight_spritesCGBPal4c1 8935
#define knight_spritesCGBPal4c2 6596
#define knight_spritesCGBPal4c3 0

/* Gameboy Color palette 5 */
#define knight_spritesCGBPal5c0 6076
#define knight_spritesCGBPal5c1 8935
#define knight_spritesCGBPal5c2 6596
#define knight_spritesCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define knight_spritesCGBPal6c0 6076
#define knight_spritesCGBPal6c1 8935
#define knight_spritesCGBPal6c2 6596
#define knight_spritesCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define knight_spritesCGBPal7c0 6076
#define knight_spritesCGBPal7c1 8935
#define knight_spritesCGBPal7c2 6596
#define knight_spritesCGBPal7c3 5344
/* CGBpalette entries. */
extern const unsigned char knight_spritesCGB[];
/* Start of tile array. */
extern const unsigned char knight_sprites[];

#endif

/* End of KNIGHT_SPRITES.H */
